### ISSUE TITLE
下载stream.x64.x-none.dat过程中卡住了

### ISSUE THREAD

**Issue by looooading** [OdysseusYuan/Mocreak#1]
![image](https://github.com/OdysseusYuan/Mocreak/assets/54234042/fe0e4602-ff24-4957-bfe4-b6d6165c5fcd)
下载到大概20%的时候开始卡住了
无论clash是全局还是直连都没什么变化，偶尔会有个几百KB/s
十分钟里大部分时间都是0B/s

**Comment by OdysseusYuan** [comment]
感谢您的使用。辛苦告知：在进度前20%的时候，您的速度大约稳定在多少？

**Comment by looooading** [comment]
> 感谢您的使用。辛苦告知：在进度前20%的时候，您的速度大约稳定在多少？

5~7MB/s

**Comment by looooading** [comment]
现在我把火绒和clash都退出了，大约稳定在100KB/s~1MB/s

**Comment by looooading** [comment]
> 目前怀疑是cdn镜像加速的原因。正在排查中。

阁下辛苦了，记得好好吃饭

**Comment by OdysseusYuan** [comment]
感谢关心。为了不影响您的使用，我已经上传了一份 预下载 的镜像文件，您可直接加载使用。
地址：[https://pan.quark.cn/s/b5e0833da221](https://pan.quark.cn/s/b5e0833da221)

加载后，APP将会自动识别为镜像模式，点选需要安装的组件后直接点击“立即安装”即可。

**Comment by OdysseusYuan** [comment]
楼主你好，此问题已经解决，可在此下载：https://github.com/OdysseusYuan/Mocreak/releases/tag/v2.0.1

测试效果如下图所示：（速度已经得到显著提升，100Mbps 的宽带稳定拉满，大文件5分钟左右下载完成。如果带宽 300Mbps 或许用时更短。）
![image](https://github.com/OdysseusYuan/Mocreak/assets/115532436/d66d6567-a43e-48ad-bd1e-a9aa599447eb)

以上，感谢你的反馈和测试，欢迎随时沟通。
