### ISSUE TITLE
360会报错

### ISSUE THREAD

**Issue by Giter124** [OdysseusYuan/Mocreak#10]
我介绍给我朋友使用的时候，她电脑上面有360，然后出现杀毒警示，我谢谢360

**Comment by OdysseusYuan** [comment]
感谢您的使用。本程序安全、可靠，请放心使用。如仍不放心，您可自行编译源代码使用本程序：https://github.com/OdysseusYuan/LKY_OfficeTools

**Comment by yankai1009** [comment]
> 感谢您的使用。本程序安全、可靠，请放心使用。如仍不放心，您可自行编译源代码使用本程序：https://github.com/OdysseusYuan/LKY_OfficeTools

请问该软件和LKY Office Tools一样，正版激活？

**Comment by OdysseusYuan** [comment]
> > 感谢您的使用。本程序安全、可靠，请放心使用。如仍不放心，您可自行编译源代码使用本程序：https://github.com/OdysseusYuan/LKY_OfficeTools
> 
> 请问该软件和LKY Office Tools一样，正版激活？

您好，Mocreak 包含 LKY Office Tools 的所有功能，具体区别详见：https://www.mocreak.com/download.html

**Comment by TrumanXia** [comment]
> > > 感谢您的使用。本程序安全、可靠，请放心使用。如仍不放心，您可自行编译源代码使用本程序：https://github.com/OdysseusYuan/LKY_OfficeTools
> > 
> > 
> > 请问该软件和LKY Office Tools一样，正版激活？
> 
> 您好，Mocreak 包含 LKY Office Tools 的所有功能，具体区别详见：https://www.mocreak.com/download.html

这个下载链接上没有说激活不激活的问题，我下载的软件界面上也没有激活选项，是安装好就默认激活了吗？

**Comment by OdysseusYuan** [comment]
> > > > 感谢您的使用。本程序安全、可靠，请放心使用。如仍不放心，您可自行编译源代码使用本程序：https://github.com/OdysseusYuan/LKY_OfficeTools
> > > 
> > > 
> > > 请问该软件和LKY Office Tools一样，正版激活？
> > 
> > 
> > 您好，Mocreak 包含 LKY Office Tools 的所有功能，具体区别详见：https://www.mocreak.com/download.html
> 
> 这个下载链接上没有说激活不激活的问题，我下载的软件界面上也没有激活选项，是安装好就默认激活了吗？

如果您的电脑符合注册条件，会直接完成注册。
