### ISSUE TITLE
Mocreak问题

### ISSUE THREAD

**Issue by RunningPig-0318** [OdysseusYuan/Mocreak#11]
1.安装office没有access

2.安装office后, 用vb编译部件提示没有 execl组件,见附件图片
![Uploading 微信图片_20240430081818.png…]()

**Comment by OdysseusYuan** [comment]
感谢您的使用。您安装的是预览版还是稳定版？

**Comment by RunningPig-0318** [comment]
稳定版



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月30日(周二) 上午8:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OdysseusYuan/Mocreak] Mocreak问题 (Issue #11)




 
感谢您的使用。您安装的是预览版还是稳定版？

**Comment by OdysseusYuan** [comment]
VB的版本是 VS 安装的嘛？还是早期 vc6.0 的并行版本？

**Comment by RunningPig-0318** [comment]
vb是安装版的，6.0，不知道是不是并行版，安装原版的office2016,2013,2010,2007,vb使用没有问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月4日(周六) 中午1:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OdysseusYuan/Mocreak] Mocreak问题 (Issue #11)




 
VB的版本是 VS 安装的嘛？还是早期 vc6.0 的并行版本？

**Comment by OdysseusYuan** [comment]
如果通过 vs 安装 vb 组件，并通过 nuget 导入 Microsoft.Office.Interop.Excel 包，有没有可能支持到您的开发环境。
