### ISSUE TITLE
卡在“正在注册office组件环境”

### ISSUE THREAD

**Issue by elanternth** [OdysseusYuan/Mocreak#13]
![image](https://github.com/OdysseusYuan/Mocreak/assets/23732994/bba3a767-de2b-4682-a710-11281e06f8b5)

注册office环境组件，安装很久。关闭后，软件是可以使用的。不注册office环境组件有影响吗？

**Comment by OdysseusYuan** [comment]
感谢您的使用。不“注册 Office 组件环境”确实会有影响，这将促使 Office 有些功能不能正常运转。

通常情况，组件注册不能顺利完成，是因为：在您未知的情况下，一些软件篡改了您的系统文件，导致文件受损，进而无法注册。

建议您重新安装干净的操作系统，尽可能在全新的系统中，安装 Office。
