### ISSUE TITLE
在部署时能否增加选择office版本的功能

### ISSUE THREAD

**Issue by 2010wukong** [OdysseusYuan/Mocreak#14]
在部署时能否增加选择office版本的功能，比方装office2016，而不是默认装最新版的

**Comment by Gynomys** [comment]
这个订阅无法退订么，完，从没看过订阅，这下隔三差五的邮件📧不知道搁哪儿退订🤣在 2024年5月15日，09:39，2010wukong ***@***.***> 写道：﻿
在部署时能否增加选择office版本的功能，比方装office2016，而不是默认装最新版的

**Comment by OdysseusYuan** [comment]
> 在部署时能否增加选择office版本的功能，比方装office2016，而不是默认装最新版的

感谢您的建议，后续将迭代此功能。

**Comment by OdysseusYuan** [comment]
> 这个订阅无法退订么，完，从没看过订阅，这下隔三差五的邮件📧不知道搁哪儿退订🤣在 2024年5月15日，09:39，2010wukong ***@***.***> 写道：﻿ 在部署时能否增加选择office版本的功能，比方装office2016，而不是默认装最新版的 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

您好，如需停用通知，可在本仓库主页点击 unwatch 按钮，并选择“ignore”即可，如下图：
![image](https://github.com/OdysseusYuan/Mocreak/assets/115532436/520a532e-055e-43b6-8244-6963a111ff97)
以上，如有问题欢迎随时沟通。

**Comment by OdysseusYuan** [comment]
> 在部署时能否增加选择office版本的功能，比方装office2016，而不是默认装最新版的

您好，Mocreak 已发布新版本，新增支持 Office 2016、2019 版本，您可尝试使用。

下载地址：https://github.com/OdysseusYuan/Mocreak/releases/latest

以上，如有问题，欢迎随时沟通。
