### ISSUE TITLE
无法获取最新的 Office 发布信息，请稍后重试！

### ISSUE THREAD

**Issue by Chef5** [OdysseusYuan/Mocreak#16]
选的是稳定安全版，把火绒关闭了也这样

![38b612644b9eddacade8fe798d620f8](https://github.com/OdysseusYuan/Mocreak/assets/38160059/5d1301bd-f714-4e88-9434-2e274986fa13)

**Comment by OdysseusYuan** [comment]
感谢您的使用。观察到您的系统UI是Win7，很遗憾，目前软件暂不支持Win7系统（https://support.microsoft.com/zh-cn/windows/windows-7-%E6%94%AF%E6%8C%81%E4%BA%8E-2020-%E5%B9%B4-1-%E6%9C%88-14-%E6%97%A5%E7%BB%88%E6%AD%A2-b75d4580-2cc7-895a-2c9c-1466d9a53962），为了您的计算机安全，建议您升级至Win10或Win11系统。
