### ISSUE TITLE
Install Office in folder

### ISSUE THREAD

**Issue by Hunter23071985** [OdysseusYuan/Mocreak#17]
Hello!
Consider installing Office in a specified folder, not only in a specified drive.
Thank you!

**Comment by OdysseusYuan** [comment]
Thank you for your use.

Previously, I had considered providing users with fully customizable paths, but due to the current operating principle of Office, Mocreak only allows users to modify the installation partition, otherwise it will not work after Office installation.

However, based on your needs, I might consider trying to meet your needs after the official release of Office 2024 (Oct), as this would require recompiling much of the Office kernel source code, so Office with support for fully customizable installation directories will probably run in parallel.

**Comment by Hunter23071985** [comment]
Thanks for your reply!
Please take a look at Office 2019 portable (password is 123)<https://disk.yandex.ru/d/kRZdNt5W6bL7Kg>.
It can be registered in any folder and works fine.
I really need the same Office 2019, which includes all apps and a Turkish interface.
Could you help me please?


________________________________
От: OdysseusYuan ***@***.***>
Отправлено: 3 июня 2024 г. 01:12
Кому: OdysseusYuan/Mocreak ***@***.***>
Копия: Hunter23071985 ***@***.***>; Author ***@***.***>
Тема: Re: [OdysseusYuan/Mocreak] Install Office in folder (Issue #17)


Thank you for your use.

Previously, I had considered providing users with fully customizable paths, but due to the current operating principle of Office, Mocreak only allows users to modify the installation partition, otherwise it will not work after Office installation.

However, based on your needs, I might consider trying to meet your needs after the official release of Office 2024 (Oct), as this would require recompiling much of the Office kernel source code, so Office with support for fully customizable installation directories will probably run in parallel.

**Comment by OdysseusYuan** [comment]
Thank you for the reference.

**Comment by Hunter23071985** [comment]
I hope you can adapt the methods of this portable to your Mocreate or LKY so that people can automatically download and deploy portable Office 2019 (and maybe newer versions) of the desired bitness and localization in a desired folder, not just in the root drive. This would be much more convenient for evaluating Office software. Good luck!

**Comment by Hunter23071985** [comment]
Hello!
I was able to download Office 2024 in the "D:\[PR]\Office 2024" folder and install in "D:\Program Files\Microsoft Office".
But how to install it in "D:\[PR]\Office 2024" and preferably X86 version on X64 OS?
This was the initial request.

**Comment by Hunter23071985** [comment]
Hello!
I wrote a comment for the new version of Mocreak in GitHub<https://github.com/odysseusyun/mocreak/issues/17>.
Also I wanted to share with you a link to the topic on bbs.wuyou.net<http://bbs.wuyou.net/forum.php?mod=Viewthread&tid=441137>.
Chinese and Russian Office 2024, based on the materials of this topic, are here<https://disk.yandex.ru/d/yE05OSoYqN8yuA>.
Please do not distribute these links! It can help you to improve Mocreak.
I really hope that this will not take much time. Thanks and good luck!
Sincerely.


________________________________
От: OdysseusYuan ***@***.***>
Отправлено: 3 июня 2024 г. 01:12
Кому: OdysseusYuan/Mocreak ***@***.***>
Тема: Re: [OdysseusYuan/Mocreak] Install Office in folder (Issue #17)


Thank you for your use.

Previously, I had considered providing users with fully customizable paths, but due to the current operating principle of Office, Mocreak only allows users to modify the installation partition, otherwise it will not work after Office installation.

However, based on your needs, I might consider trying to meet your needs after the official release of Office 2024 (Oct), as this would require recompiling much of the Office kernel source code, so Office with support for fully customizable installation directories will probably run in parallel.
