### ISSUE TITLE
可以不可以让我们自定义选择下载哪个具体的office版本，谢谢。

### ISSUE THREAD

**Issue by xingyeyeyeye** [OdysseusYuan/Mocreak#19]
我想下载一些以前的老版本。

**Comment by OdysseusYuan** [comment]
感谢您的使用。您提及的“版本”是指“2016”、“2019”这种版本么？

**Comment by xingyeyeyeye** [comment]
> 感谢您的使用。您提及的“版本”是指“2016”、“2019”这种版本么？
> 
> 感谢您的使用。您提及的“版本”是指“2016”、“2019”这种版本么？

对的

**Comment by OdysseusYuan** [comment]
感谢您的建议，后续迭代将尝试开发上线。

**Comment by OdysseusYuan** [comment]
您好，Mocreak 已发布新版本，新增支持 Office 2016、2019 版本，您可尝试使用。

下载地址：https://github.com/OdysseusYuan/Mocreak/releases/latest

以上，如有问题，欢迎随时沟通。
