### ISSUE TITLE
提示这个问题

### ISSUE THREAD

**Issue by cjztool** [OdysseusYuan/Mocreak#2]
正在安装 稳定安全版 Office 组件 与 汉语 - 简体中文 语言组件 ...... 失败！

怎么搞呢

**Comment by OdysseusYuan** [comment]
感谢您的使用。新版本已修复您提到的问题，详见：https://github.com/OdysseusYuan/Mocreak/releases/tag/v2.1.0
欢迎下载体验，如有问题欢迎随时沟通。

**Comment by cjztool** [comment]
> 感谢您的使用。新版本已修复您提到的问题，详见：https://github.com/OdysseusYuan/Mocreak/releases/tag/v2.1.0 欢迎下载体验，如有问题欢迎随时沟通。

3q
