### ISSUE TITLE
ARM架构支持

### ISSUE THREAD

**Issue by LuckyZhiOfficial** [OdysseusYuan/Mocreak#21]
目前在用arm的win11，看到log里面下载的是x64的Office，能否支持下载arm版本的呢？
<img width="1010" alt="Screenshot 2024-07-01 at 17 04 48" src="https://github.com/OdysseusYuan/Mocreak/assets/52288096/1c0ae8df-f590-4922-8cd3-3b10c77bc7da">

**Comment by OdysseusYuan** [comment]
感谢您的使用。目前 Mocreak 尚未明确支持 ARM64 架构的 Office，后续会展开相关评估。
