### ISSUE TITLE
由于重要的系统文件丢失(或损坏),因此,您只能在短时间内,使用部分Office功能!

### ISSUE THREAD

**Issue by ZUIMKI** [OdysseusYuan/Mocreak#25]
![image](https://github.com/OdysseusYuan/Mocreak/assets/28524623/84763d8b-0fde-4cb0-aa90-2d7cd9a4eae6)

**Comment by OdysseusYuan** [comment]
感谢您的使用。

这可能是您的系统文件受损，导致 Office 无法完成组件注册。建议您重新安装系统。
