### ISSUE TITLE
请问有支持win7的版本或者办法吗

### ISSUE THREAD

**Issue by matocool** [OdysseusYuan/Mocreak#27]
请问有支持win7的版本或者办法吗

**Comment by OdysseusYuan** [comment]
感谢您的使用。很遗憾，微软在 4 年前已经宣布停止针对 Win7 系统的全部支持，包括但不限于：系统、Office 等应用软件，具体可参考：https://support.microsoft.com/zh-cn/windows/windows-7-%E6%94%AF%E6%8C%81%E4%BA%8E-2020-%E5%B9%B4-1-%E6%9C%88-14-%E6%97%A5%E7%BB%88%E6%AD%A2-b75d4580-2cc7-895a-2c9c-1466d9a53962

个人建议，由于 Win7 系统相比于今天的系统存在更多的安全问题，故建议您升级至 Win10 或更高的系统。

如果您必须使用 Win7 环境，可尝试 Google 关键词，形如：`cn_office_professional_plus_2013_x86_x64_dvd_1149708.iso` 检视下载。
