### ISSUE TITLE
可以出一个便携版本的吗？

### ISSUE THREAD

**Issue by blackdarks** [OdysseusYuan/Mocreak#3]
大佬您好，能否辛苦您安排一个绿色便携版本的该软件？谢谢啦。

**Comment by OdysseusYuan** [comment]
感谢您的使用。您的需求十分重要，现已排进后续迭代的需求池，陆续将上线，敬请期待。

**Comment by OdysseusYuan** [comment]
您好，Mocreak 便携版 已经发布，具体详见：https://github.com/OdysseusYuan/Mocreak/releases/latest

上述链接，含有“Portable”字样的压缩包即为所需。

如有问题欢迎随时沟通，感谢您的支持。
