### ISSUE TITLE
Install Office in folder 2

### ISSUE THREAD

**Issue by Hunter23071985** [OdysseusYuan/Mocreak#33]
Hello!
Congratulations on the new program release!
But when will it be possible to install Office in the specified folder?

**Comment by OdysseusYuan** [comment]
Thank you for your interest, this requirement is under consideration and specific development details will be finalized at a later stage.

**Comment by OdysseusYuan** [comment]
Hello, the above requirements need to be further evaluated, especially the third may involve mocreak's own product positioning issues - AI-based functions, may involve gpt product policy, or related legal issues, with further evaluation and reply to you. Thank you for your suggestion.
