### ISSUE TITLE
注册office组件失败

### ISSUE THREAD

**Issue by JiafengLiao** [OdysseusYuan/Mocreak#37]
![image](https://github.com/user-attachments/assets/14673eb0-17fd-438e-bb27-64ce1eac38c7)

**Comment by JiafengLiao** [comment]
环境为Win11，执行了卸载后重启，安装

**Comment by OdysseusYuan** [comment]
感谢您的使用。在使用 mocreak 前，您系统中负责 office 部署的原生组件可能已被篡改。如有可能建议您重新安装系统，以确保系统的完整性。
