### ISSUE TITLE
正在注册 Office 组件环境，共计 6 个组件 ...... 第 7 次尝试中 ....

### ISSUE THREAD

**Issue by JavaHackSen** [OdysseusYuan/Mocreak#7]
![image](https://github.com/OdysseusYuan/Mocreak/assets/37896126/8a8415fd-d9ae-40e4-9e4f-f14bf7c3799e)

这种怎么解决？

**Comment by OdysseusYuan** [comment]
感谢您的使用。通常情况，这是由于您的系统文件发生损坏。请尝试重新安装 Windows 系统，理应解决。
