### ISSUE TITLE
选在安装在d盘但office实际位置依然在c盘

### ISSUE THREAD

**Issue by rEco1LLLL** [OdysseusYuan/Mocreak#8]

**Comment by OdysseusYuan** [comment]
感谢您的使用。在您C盘出现的Office目录图标是否出现了一个类似快捷方式的箭头？并且d盘已经出现了Office目录？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月13日(周三) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OdysseusYuan/Mocreak] 选在安装在d盘但office实际位置依然在c盘 (Issue #8)

**Comment by rEco1LLLL** [comment]
> 感谢您的使用。在您C盘出现的Office目录图标是否出现了一个类似快捷方式的箭头？并且d盘已经出现了Office目录？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月13日(周三) 中午11:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [OdysseusYuan/Mocreak] 选在安装在d盘但office实际位置依然在c盘 (Issue #8) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

<img width="723" alt="Snipaste_2024-03-13_12-01-05" src="https://github.com/OdysseusYuan/Mocreak/assets/112418478/bcdbbd9f-aa7d-4aed-99d1-045b2fa8a74d">
<img width="1193" alt="Snipaste_2024-03-13_12-01-56" src="https://github.com/OdysseusYuan/Mocreak/assets/112418478/785a2452-faaf-47cd-9109-f9b7de94c15c">
如图是c盘与d盘文件的对比

**Comment by rEco1LLLL** [comment]
> 感谢您的使用。在您C盘出现的Office目录图标是否出现了一个类似快捷方式的箭头？并且d盘已经出现了Office目录？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月13日(周三) 中午11:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [OdysseusYuan/Mocreak] 选在安装在d盘但office实际位置依然在c盘 (Issue #8) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我在两台计算机上的安装情况都是这样，实际位置在c盘

**Comment by OdysseusYuan** [comment]
您好，辛苦截图如下路径的图标。
![image](https://github.com/OdysseusYuan/Mocreak/assets/115532436/3079f856-985b-4796-ad17-ee2bd18c6286)

**Comment by rEco1LLLL** [comment]
> 您好，辛苦截图如下路径的图标。 ![image](https://private-user-images.githubusercontent.com/115532436/312311790-3079f856-985b-4796-ad17-ee2bd18c6286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDU1MjUsIm5iZiI6MTcxMDMwNTIyNSwicGF0aCI6Ii8xMTU1MzI0MzYvMzEyMzExNzkwLTMwNzlmODU2LTk4NWItNDc5Ni1hZDE3LWVlMmJkMThjNjI4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwNDQ3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2I5OWIzNjhlYTVjNWUwNGQ4MWRhMGQ5NzI2Yjg4OTMxY2I2ZmJiYWU3MjM0ZGQ1MDhiYzA5ZTY1YWU2MTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D0IyfUc3fcRMJj2KUVJRq9rjbIc-l-Elsgim7FzRyVI)
![Uploading Snipaste_2024-03-13_12-48-12.png…]()

**Comment by rEco1LLLL** [comment]
> 您好，辛苦截图如下路径的图标。 ![image](https://private-user-images.githubusercontent.com/115532436/312311790-3079f856-985b-4796-ad17-ee2bd18c6286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDU2MTcsIm5iZiI6MTcxMDMwNTMxNywicGF0aCI6Ii8xMTU1MzI0MzYvMzEyMzExNzkwLTMwNzlmODU2LTk4NWItNDc5Ni1hZDE3LWVlMmJkMThjNjI4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwNDQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Zjc0OGM2NGEyZjQ1M2Y2ODhjNGJhNDQ2MTNhNDJjODk0ZjBhNzcyNWE1YTkzMTc0ZDMzZWFjMTk0MTAwMTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-08p2db_fNQEmiGohWBJd1L_lpxNwMyce9ZXuolC2vo)

<img width="536" alt="Snipaste_2024-03-13_12-48-12" src="https://github.com/OdysseusYuan/Mocreak/assets/112418478/45fd9a17-19bc-4e59-b694-2bbc82d64d32">

**Comment by OdysseusYuan** [comment]
您好，据图所示，您应该是已经成功安装到了D盘，目前C盘中的这个目录只是一个跳转标记（Office不会占用C盘空间），当您进入该文件夹后，理应实际进入的是D盘目录。

如果您想验证上述结论，可以尝试在 D:\Program Files\Microsoft Office 目录中新建一个txt文件，此时回到截图中的目录，您会发现，该目录下出现了您刚刚新建的txt文件。

**Comment by rEco1LLLL** [comment]
> 您好，据图所示，您应该是已经成功安装到了D盘，目前C盘中的这个目录只是一个跳转标记（Office不会占用C盘空间），当您进入该文件夹后，理应实际进入的是D盘目录。
> 
> 如果您想验证上述结论，可以尝试在 D:\Program Files\Microsoft Office 目录中新建一个txt文件，此时回到截图中的目录，您会发现，该目录下出现了您刚刚新建的txt文件。

抱歉，好像确实是这样
